#!/bin/sh
# Warn if [TODO]s present in ./docs before commit
if grep -r '\[TODO\]' ./docs; then
  echo "[WARN] There are unresolved [TODO]s in ./docs. Please address before committing."
fi
# (Optional) Add more checks for 'Last Reviewed' freshness or other doc signals.
