# CodeRabbit Configuration File
# Documentation: https://docs.coderabbit.ai/getting-started/configure-coderabbit/

# Basic configuration
version: 1
early_access: true

# Review settings
reviews:
  high_level_summary: true
  poem: true
  review_checklist: true
  auto_review:
    enabled: true
    ignore_title_patterns:
      - "^WIP:.*"
      - "^Draft:.*"
    drafts: false
    base_branches:
      - main
      - develop
    labels:
      - ai-review
  
  # Customize the review comment triggers
  comment_triggers:
    - "@coderabbit review"
    - "@coderabbit please review"
    - "@coderabbit review file"
  
  # Customize the review thresholds
  thresholds:
    downvote_threshold: 2
    upvote_threshold: 2
    
  # Customize the paths to include/exclude from reviews
  path_filters:
    - "!backend/smart-contract/lib/**"
    - "!node_modules/**"
    - "!**/dist/**"
    - "!**/*.min.js"
    - "!**/*.min.css"
    - "!**/*.lock"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.ico"
    - "!**/*.woff"
    - "!**/*.woff2"
    - "!**/*.ttf"
    - "!**/*.eot"
    - "!**/*.pdf"
    - "!**/*.zip"
    - "!**/*.tar.gz"
    - "!**/*.tgz"
    - "!**/*.gz"
    - "!**/*.rar"
    - "!**/*.7z"

# Chat settings
chat:
  auto_reply: true

# Using free public CodeRabbit service
# No model settings needed as we're using the public version
