version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      bun-and-ts:
        patterns:
          - "bun*"
          - "@biomejs/*"
          - "typescript"
          - "@typescript/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
