/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeSwapRouteImport } from './routes/trade/swap'
import { Route as TradeSendRouteImport } from './routes/trade/send'
import { Route as TradeLiquidityRouteImport } from './routes/trade/liquidity'
import { Route as TradeLimitRouteImport } from './routes/trade/limit'
import { Route as TradeBuyRouteImport } from './routes/trade/buy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSwapRoute = TradeSwapRouteImport.update({
  id: '/trade/swap',
  path: '/trade/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSendRoute = TradeSendRouteImport.update({
  id: '/trade/send',
  path: '/trade/send',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeLiquidityRoute = TradeLiquidityRouteImport.update({
  id: '/trade/liquidity',
  path: '/trade/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeLimitRoute = TradeLimitRouteImport.update({
  id: '/trade/limit',
  path: '/trade/limit',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeBuyRoute = TradeBuyRouteImport.update({
  id: '/trade/buy',
  path: '/trade/buy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trade/buy': typeof TradeBuyRoute
  '/trade/limit': typeof TradeLimitRoute
  '/trade/liquidity': typeof TradeLiquidityRoute
  '/trade/send': typeof TradeSendRoute
  '/trade/swap': typeof TradeSwapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trade/buy': typeof TradeBuyRoute
  '/trade/limit': typeof TradeLimitRoute
  '/trade/liquidity': typeof TradeLiquidityRoute
  '/trade/send': typeof TradeSendRoute
  '/trade/swap': typeof TradeSwapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trade/buy': typeof TradeBuyRoute
  '/trade/limit': typeof TradeLimitRoute
  '/trade/liquidity': typeof TradeLiquidityRoute
  '/trade/send': typeof TradeSendRoute
  '/trade/swap': typeof TradeSwapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trade/buy'
    | '/trade/limit'
    | '/trade/liquidity'
    | '/trade/send'
    | '/trade/swap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trade/buy'
    | '/trade/limit'
    | '/trade/liquidity'
    | '/trade/send'
    | '/trade/swap'
  id:
    | '__root__'
    | '/'
    | '/trade/buy'
    | '/trade/limit'
    | '/trade/liquidity'
    | '/trade/send'
    | '/trade/swap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradeBuyRoute: typeof TradeBuyRoute
  TradeLimitRoute: typeof TradeLimitRoute
  TradeLiquidityRoute: typeof TradeLiquidityRoute
  TradeSendRoute: typeof TradeSendRoute
  TradeSwapRoute: typeof TradeSwapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/swap': {
      id: '/trade/swap'
      path: '/trade/swap'
      fullPath: '/trade/swap'
      preLoaderRoute: typeof TradeSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/send': {
      id: '/trade/send'
      path: '/trade/send'
      fullPath: '/trade/send'
      preLoaderRoute: typeof TradeSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/liquidity': {
      id: '/trade/liquidity'
      path: '/trade/liquidity'
      fullPath: '/trade/liquidity'
      preLoaderRoute: typeof TradeLiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/limit': {
      id: '/trade/limit'
      path: '/trade/limit'
      fullPath: '/trade/limit'
      preLoaderRoute: typeof TradeLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/buy': {
      id: '/trade/buy'
      path: '/trade/buy'
      fullPath: '/trade/buy'
      preLoaderRoute: typeof TradeBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradeBuyRoute: TradeBuyRoute,
  TradeLimitRoute: TradeLimitRoute,
  TradeLiquidityRoute: TradeLiquidityRoute,
  TradeSendRoute: TradeSendRoute,
  TradeSwapRoute: TradeSwapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
