[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 1000
via_ir = true
ffi = true # General ffi for default profile
# Security settings
strict = true
revert_strings = 'strip' # This will affect vm.expectRevert(bytes("message")) style tests

    [profile.default.vyper]
    version = "0.3.10"
    # path = "/home/swebot/.local/bin/vyper" # REMOVED - Let Foundry find Vyper in system PATH
    # Let Foundry find Vyper in PATH instead of using a hardcoded path that won't work in CI

# [profile.remappings] section removed to defer to remappings.txt

[profile.test]
# ffi = true # Assuming default ffi=true is sufficient, or can be re-added if test needs specific
fuzz_runs = 500

[rpc_endpoints]
polygonzkevm = 'https://polygonzkevm-cardona.g.alchemy.com/v2/Ys7mXBCGPyrC30IezKb1b362vYOI1XBL'

[fmt]
line_length = 120

[fuzz]
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.ci]
ffi = false
no_match_test = "(Integration|Fork)"
rpc_endpoints = {}
