[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'

    [profile.default.vyper]
    version = "0.3.10"
    # Let Foundry find Vyper in PATH instead of using a hardcoded path that won't work in CI

[profile.remappings]
'forge-std' = 'lib/forge-std/src/'
'@openzeppelin/contracts/' = 'lib/openzeppelin-contracts/contracts/' # Revert to standard
'v4-core/' = 'lib/v4-core/src/' # Use v4-core key
'v4-core/interfaces/' = 'lib/v4-core/src/interfaces/' # Use v4-core key

[profile.compiler]
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 1000
via_ir = true
ffi = true
# Security settings
strict = true
revert_strings = 'strip'

[profile.test]
ffi = true
fuzz_runs = 500

[rpc_endpoints]
polygonzkevm = 'https://polygonzkevm-cardona.g.alchemy.com/v2/Ys7mXBCGPyrC30IezKb1b362vYOI1XBL'

[fmt]
line_length = 120

[fuzz]
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.ci]
ffi = false
no_match_test = "(Integration|Fork)"
rpc_endpoints = {}
