[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'

[profile.remappings]
'forge-std' = 'lib/forge-std/src/'
'@openzeppelin/contracts' = 'lib/openzeppelin-contracts/contracts/'

[profile.compiler]
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
polygonzkevm = 'https://polygonzkevm-cardona.g.alchemy.com/v2/Ys7mXBCGPyrC30IezKb1b362vYOI1XBL'

[fmt]
line_length = 120

[profile.test]
ffi = true
