name: Smart Contract Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/smart-contract/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/smart-contract/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run tests
        run: |
          cd backend/smart-contract
          forge test
